runtime! configs/settings.vim
runtime! configs/nerdtree.vim
runtime! configs/keymappings.vim
runtime! configs/functions.vim
runtime! configs/colorscheme.vim
runtime! configs/statusline.vim
runtime! configs/custom_statusline.vim
runtime! configs/coc.vim
runtime! configs/plugins.vim
